### ISSUE TITLE
默的抗拒接触未受到魔攻葡萄的加成

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#10]
**如果现在魔攻葡萄不再加成抗拒接触了，请当我没说**
如图，在测试中，默携带10%魔攻葡萄和未携带葡萄的抗拒接触伤害几乎一致（34236；34235）
![屏幕截图 2023-05-22 120321](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/6416e278-2683-4814-b803-3c30200a03bc)
![屏幕截图 2023-05-22 120347](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/7fb8c4ab-5f35-4315-90a2-db80516e076b)

```
测试用数据：
XI G=100000 850 900 7 11
WISH 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 1 1 1000 1 1000
NONE
NONE
WOOD 300 150 60 60 60 0
NONE
0

MO_无魔攻葡萄 850 900 7 11
WISH 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 1 1 1 900 1
NONE
NONE
CLOAK 300 100 100 150 150 1
NONE
0

MO_10%魔攻葡萄 850 900 7 11
WISH 0 0 0 0 0 0 0 0 0 0 0 0 0 0
AMULET MATK 10 ENDAMULET
1 1 1 1 900 1
NONE
NONE
CLOAK 300 100 100 150 150 1
NONE
```

**Comment by ilusrdbb** [comment]
护盾能量最大值+40%，每次被普通攻击都会返还(50%魔法攻击+8%最大护盾值)的魔法伤害给对方。
这里我只对50%魔法攻击进行了魔攻葡萄的加成，不清楚魔攻葡萄加成反伤是否要包含最大护盾值的部分

**Comment by Mulexe** [comment]
> 护盾能量最大值+40%，每次被普通攻击都会返还(50%魔法攻击+8%最大护盾值)的魔法伤害给对方。 这里我只对50%魔法攻击进行了魔攻葡萄的加成，不清楚魔攻葡萄加成反伤是否要包含最大护盾值的部分

应该包含了最大护盾值的部分

例如这场，将防守方的苹果樱桃、剑盾反伤、争夺等级给到最大值后，抗拒接触+反伤的伤害仍然差了大约10%
![屏幕截图 2023-05-22 195007](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/3a0f9a77-32e1-4147-9ca4-dc6c71a19eba)
![屏幕截图 2023-05-22 205713](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/04c133ab-9129-4b9c-968b-9fdad6c50baf)

再补一个纯护盾默的情况，也是差大约10%
![屏幕截图 2023-05-23 011448](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/8bb1c133-f035-45cc-bcfa-7ded2ce004e7)
![屏幕截图 2023-05-23 011713](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/f640959c-74f6-4746-a2d5-c3648e2ea4ec)

**Comment by ilusrdbb** [comment]
感谢提供对战数据，我这边计算确实有偏差，此问题已修正
