### ISSUE TITLE
冥的命运链接和反伤 与 攻防等级的关系

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#11]
`（PVP）当自身进攻等级高于对方，高出部分每级+3%伤害加深（差距上限20级）`
`（PVP）当自身防御等级高于对方，高出部分每级+3%伤害减免（差距上限20级）`

**1、攻防等级低的实际情况**
如图，左侧冥的攻防等级低1级，但计算器数值比实际的反伤+命运链接魔伤高了大约3%，命运链接提供的物伤也高了3%
![屏幕截图 2023-05-25 160335](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/54537344-e2f5-451e-a773-e258009b6f68)
![image](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/d3275d7b-4bd1-4dfd-b4cc-9fb7095c77f3)

**2、攻防等级相同的实际情况**
计算器与实际反伤和命运链接的数值相符
![屏幕截图 2023-05-25 180135](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/d490896f-8b8d-465b-a644-898b9eb3b578)
![屏幕截图 2023-05-25 180047](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/2f3c2143-e945-48d3-9717-74759e84f44e)

**3、攻防等级高的实际情况**
当左侧冥的攻防等级高1级时，计算器算出的反伤低了大约6%
![屏幕截图 2023-05-25 181125](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/3adfb47b-327a-40a8-b8ce-1ed8349beab4)
![屏幕截图 2023-05-25 181108](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/3de170e0-84f5-4ffe-9cf4-c956f4c75ea1)

**我猜测进攻等级的描述有误，实际当进攻等级不同时，不仅会增加等级高一方的伤害（并且这个伤害包括反伤和命运链接），还会降低等级低一方的伤害（也包括反伤和命运链接）**
- 进攻等级加强的伤害包括反伤和可以降低对方伤害 可以解释情况3的6%差距
- 进攻等级降低的伤害包括反伤 可以解释情况1的3%差距

**当然，也可能是单纯地把进攻等级每级的3%改成了6%，同时增强的伤害包括反伤和命运链接**

**Comment by ilusrdbb** [comment]
检查了下代码，发现反伤漏加了进攻和防御等级的计算==
对于第一条结果能解释的通，就是没计算防御等级，但是第三条的6%无法解释，如果进攻等级还能降低对方的伤害那第一条应该也是6%才对，确定第三条对方低1级而不是2级吗

**Comment by Mulexe** [comment]
> 检查了下代码，发现反伤漏加了进攻和防御等级的计算== 对于第一条结果能解释的通，就是没计算防御等级，但是第三条的6%无法解释，如果进攻等级还能降低对方的伤害那第一条应该也是6%才对，确定第三条对方低1级而不是2级吗

感谢修复。
确实有低2级的可能，缺乏明确的案例，后续再观察吧

另，此次修复后情况1里的对方承伤已经正确，反伤和命运链接的伤害仍然偏高，虽然不影响实际使用，但为了后续观察问题，能否将反伤的伤害一并修改以符合战斗记录呢
![屏幕截图 2023-05-26 135128](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/188819b7-5f74-4f73-81f5-af0f71f038c8)
![屏幕截图 2023-05-25 160335](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/54537344-e2f5-451e-a773-e258009b6f68)

**Comment by ilusrdbb** [comment]
显示已修正
