### ISSUE TITLE
1400争夺的效果未正确生效 与 特定条件下面板伤害显示错误

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#12]
**1.** ![image](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/d5d95468-afcc-4fc1-8003-b0310755724f)

防守方确定有1400争夺，游戏中其拥有855918点护盾；10w成长值、全150%装备的情况下，计算器中只有298983点护盾
![屏幕截图 2023-05-31 032057](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/63d90303-60a2-4ee9-b09f-4bd31804c73b)
![屏幕截图 2023-05-31 033026](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/53e2423b-4c95-4d38-9a92-5a6ec0881d45)

**2.** 
若攻击方的争夺等级更低，会使得攻击的面板伤害过高，但对方的反伤和承伤是正确的，应该只是显示错误。

`（左1000争夺，右确定1400争夺）`
![屏幕截图 2023-05-31 050155](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/d4bf33fa-1ba9-4133-a0b3-53e3feda0812)
![屏幕截图 2023-05-31 050444](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/fdb82523-7d4e-4e47-a511-e4cb94b47a9e)

**Comment by ilusrdbb** [comment]
这俩问题都已修正
今天工作比较忙，如果还有问题我下班之后再看（

**Comment by Mulexe** [comment]
> 这俩问题都已修正 今天工作比较忙，如果还有问题我下班之后再看（

感谢修复，目前看没问题了
