### ISSUE TITLE
在暴击+技能时，琳造成的绝伤偏高

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#13]
**忽视了技能抵抗效果的问题**
> 爆裂双刃  主动技能，造成(300%物理攻击力)的物理伤害和(300%物理攻击力)的魔法伤害。

左侧进攻方均为1000争夺，右侧防守方均为1100争夺
如图，均是在 2暴击 时，绝伤正常；在 3暴击+技能 时，绝伤偏高

**———————————————第一场—————————————————————————**
![屏幕截图_20230617_204927](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/1721c6ae-3b43-4e32-b15b-9d7d6e1500c1)
![屏幕截图_20230617_205118](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/fe48afcd-4239-4d0c-9be8-c2fd7f11354e)

**———————————————第二场—————————————————————————**
![屏幕截图_20230617_211226](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/f7f97a27-9ebc-4bea-8070-20cab54f50d6)
![屏幕截图_20230617_210853](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/62bf4036-a9d8-41c7-9efc-d284a522827f)

**Comment by ilusrdbb** [comment]
推测是对方带了两个技能抵抗樱桃，且抵抗樱桃影响面板，实际最终伤害应该大致一致

**Comment by ilusrdbb** [comment]
这个问题明天我再观察，如果确认是抵抗樱桃影响战斗面板显示的问题，明天会修正

**Comment by Mulexe** [comment]
> 推测是对方带了两个技能抵抗樱桃，且抵抗樱桃影响面板，实际最终伤害应该大致一致

感谢查看，纳入技能抵抗的影响后就与战斗记录一致了，我的问题
