### ISSUE TITLE
部分许愿池项目 超过512后没有正确发挥作用

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#14]
“生命值上限 每级+12”在511以下时血量加成正常，当其超过512时，血量加成似乎归零从新计算了
经测试“护盾值上限、附加魔法伤害、附加物理伤害”也有同样的情况

```
MIN_200 850 1100 7 11
WISH 0 0 0 0 0 0 0 200 0 0 0 0 0 0
AMULET  ENDAMULET
1 1 1 1 1 1
NONE
NONE
NONE
NONE
0
```

WU Lv.850  VS  MIN_**200** Lv.850
HP:91 SLD:84  --  **HP:2470** SLD:65

```
MIN_500 850 1100 7 11
WISH 0 0 0 0 0 0 0 500 0 0 0 0 0 0
AMULET  ENDAMULET
1 1 1 1 1 1
NONE
NONE
NONE
NONE
0
```
WU Lv.850  VS  MIN_**500** Lv.850
HP:91 SLD:84  --  **HP:2998** SLD:65

```
MIN_512 850 1100 7 11
WISH 0 0 0 0 0 0 0 512 0 0 0 0 0 0
AMULET  ENDAMULET
1 1 1 1 1 1
NONE
NONE
NONE
NONE
0
```
WU Lv.850  VS  MIN_**512** Lv.850
HP:91 SLD:84  --  **HP:70** SLD:65

```
MIN_513 850 1100 7 11
WISH 0 0 0 0 0 0 0 513 0 0 0 0 0 0
AMULET  ENDAMULET
1 1 1 1 1 1
NONE
NONE
NONE
NONE
0
```
WU Lv.850  VS  MIN_**513** Lv.850
HP:91 SLD:84  --  **HP:82** SLD:65

**Comment by ilusrdbb** [comment]
非常隐蔽的问题，居然能发现，太强了（扑通
原因是b大当时把许愿池点数设置为了1字节导致点数超过255会溢出，改为2字节就没问题了
