### ISSUE TITLE
雅未被添加权重

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#15]
下面是历史数据，“優くん”使用的是雅，角色名前方没有“W=1”的权重
![image](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/e49ccbd1-458d-4cfe-922b-7903b58076ee)
[韭菜收割机历史数据.zip](https://github.com/ilusrdbb/guguzhen-loganalysis/files/12035172/default.zip)

**Comment by ilusrdbb** [comment]
问题已修正
