### ISSUE TITLE
收割机的防守数据导致报错

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#16]
原帖：read.php?tid=1000914&sf=823

报错如下（关闭太快只能录像截图了）：
![image](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/a6f2fc93-0a00-4948-b455-fe1d373e0089)

新加的防守数据如下：
`{"id":"213d8bf84201c7801a4b9ebfee4a6558","username":"mulexe","log":"\n\t\t<div class=\"col-md-2\"><div class=\"alert fyg_f18 fyg_tc\">今天 00时</div></div>\n\t\t<div class=\"col-md-1\"><div class=\"alert alert-primary fyg_f18 fyg_tc\">守</div></div>\n\t\t<div class=\"col-md-1\"><div class=\"alert fyg_f18 fyg_tc\">平</div></div>\n\t\t<div class=\"col-md-3\"><div class=\"alert alert-info fyg_f18 fyg_tc\">[对手] lizihao0227</div></div>\n\t\t<div class=\"col-md-2\"><div class=\"alert alert-info fyg_f18 fyg_tc\">Lv.850 霞</div>\n\t\t</div>\n\t\t<div class=\"col-md-3\"><div class=\"alert alert-info fyg_f18 fyg_tc\">\n\t\t<img src=\"ys/icon/z/z2106_4.gif\" title=\"幽梦匕首\" height=\"24\">\n\t\t<img src=\"ys/icon/z/z2202_4.gif\" title=\"命师的传承手环\" height=\"24\">\n\t\t<img src=\"ys/icon/z/z2304_5.gif\" title=\"旅法师的灵光袍\" height=\"24\">\n\t\t<img src=\"ys/icon/z/z2402_4.gif\" title=\"占星师的耳饰\" height=\"24\">\n\t\t</div></div>\n\t\t","isWin":0,"enemyname":"lizihao0227","char":"霞","charlevel":"850","weapon":"DAGGER","armor":"CLOAK","invalids":0,"time":1691254793000,"equip":"<span class=\" fyg_f18 fyg_tc\">\n\t\t<img src=\"ys/icon/z/z2106_4.gif\" title=\"幽梦匕首\" height=\"24\">\n\t\t<img src=\"ys/icon/z/z2202_4.gif\" title=\"命师的传承手环\" height=\"24\">\n\t\t<img src=\"ys/icon/z/z2304_5.gif\" title=\"旅法师的灵光袍\" height=\"24\">\n\t\t<img src=\"ys/icon/z/z2402_4.gif\" title=\"占星师的耳饰\" height=\"24\">\n\t\t</span>","type":"defense","$types":{"invalids":"undef","time":"date"}}`

**Comment by ilusrdbb** [comment]
呃呃呃，新脚本导出文件是进攻防守记录都混在一块了么，我还没更新收割机，等我下班后看看吧
日后考虑把防守记录加进生成pc的权重上

**Comment by Mulexe** [comment]
> 呃呃呃，新脚本导出文件是进攻防守记录都混在一块了么，我还没更新收割机，等我下班后看看吧 日后考虑把防守记录加进生成pc的权重上

对，出击和防守记录混在一起的

**Comment by ilusrdbb** [comment]
已发布更新，目前暂时跳过防守记录
