### ISSUE TITLE
关于史莱姆和雅

### ISSUE THREAD

**Issue by kizunahitotsu** [ilusrdbb/guguzhen-loganalysis#17]
技能「手脚并用」效果为：物伤+=物攻\*3，魔伤+=魔攻\*3，**_绝伤+=(物攻+魔攻)_** 该部分会受到黑夜雅被动的影响。
目前绝伤部分的实现是绝伤+=绝对攻击\*12，与实际不符。

技能「黑发海洋」效果分3步：**_物攻_**+=(对方最大生命+最大护盾)\*0.05，对方最大生命/最大护盾\*=0.95，物伤+=物攻*3。
目前的实现是物伤+=(对方最大生命+最大护盾)\*0.15，对方最大生命/最大护盾\*=0.95，与实际不符。

另外测试时，仅有「逐渐疯狂」生效时，雅的物伤、魔伤、绝伤均与实际不符：
实际为物伤递增、魔伤不变，计算器为物伤、魔伤均递增，猜想是因为(20%物理攻击力和20%魔法攻击力)的后半部分加给了魔伤。
**_「逐渐疯狂」增加的物伤可以暴击。_**
绝伤不变，但是计算器内绝伤比实际低了一截，猜想是因为计算器内FENG生效写在了计算神秘刃绝伤之后，实际应该先计算FENG和「黑发海洋」增加的物攻再计算神秘刃绝伤。

**Comment by ilusrdbb** [comment]
> 技能「手脚并用」效果为：物伤+=物攻*3，魔伤+=魔攻*3，**_绝伤+=(物攻+魔攻)_** 该部分会受到黑夜雅被动的影响。 目前绝伤部分的实现是绝伤+=绝对攻击*12，与实际不符。
> 
> 技能「黑发海洋」效果分3步：**_物攻_**+=(对方最大生命+最大护盾)*0.05，对方最大生命/最大护盾*=0.95，物伤+=物攻*3。 目前的实现是物伤+=(对方最大生命+最大护盾)*0.15，对方最大生命/最大护盾*=0.95，与实际不符。
> 
这个没问题

> 另外测试时，仅有「逐渐疯狂」生效时，雅的物伤、魔伤、绝伤均与实际不符： 实际为物伤递增、魔伤不变，计算器为物伤、魔伤均递增，猜想是因为(20%物理攻击力和20%魔法攻击力)的后半部分加给了魔伤。 **_「逐渐疯狂」增加的物伤可以暴击。_** 

这个代码错误，不小心把魔伤也算上了

> 绝伤不变，但是计算器内绝伤比实际低了一截，猜想是因为计算器内FENG生效写在了计算神秘刃绝伤之后，实际应该先计算FENG和「黑发海洋」增加的物攻再计算神秘刃绝伤。

我觉得可能是没计算上一次黑发海洋增加的物攻导致的，关于FENG和神秘刃的顺序是b大的代码一直没改过，而且当前回合的技能在暴击之前生效是反直觉的，我认为改好黑发海洋的效果应该就没问题了

**Comment by kizunahitotsu** [comment]
![战斗记录1](https://p.inari.site/guest/23-09/11/64fe6c6bd5030.png)
己方数据：
```
YA M=1 850 1172 7 10
WISH 100 100 100 100 100 127 127 141 141 45 48 50 57 39
AMULET STR 19 AGI 48 INT 35 VIT 7 SPR 55 MND 2 PATK 10 SPD 10 SLD 10 LCH 2 RFL 5 CRT 5 SKL 3 PDEF 7 MDEF 3 AAA 8 CRTR 3 ENDAMULET
785 1073 1 1 950 1
BLADE 291 127 127 108 150 1
RING 286 150 106 119 150 0
CLOAK 300 81 78 148 109 1
TIARA 294 118 150 150 98 0
7 XIN FENG DUN SHANG ZHI JU JUE
```
计算过程如下：己方面板物攻=54039，面板魔攻=1075，速度（计算JU和护符后）=10522，
实际物攻=54039+25500(FENG)=79539，实际魔攻=1075+25500(FENG)=26575
实际物伤（非暴击）=(物攻+(物攻+魔攻)\*0.2\*回合数)\*1.1(护符)
实际物伤（暴击）=上面的\*2
绝伤（暴击）=物攻/2+速度*2.4
代入回合数是刚好吻合的。

**Comment by kizunahitotsu** [comment]
![战斗记录2](https://p.inari.site/guest/23-09/11/64fe701fa628d.png)
己方数据：
```
YA M=0 850 1173 7 10
WISH 100 100 100 100 100 127 127 141 141 45 48 50 57 39
AMULET STR 19 AGI 48 INT 35 VIT 7 SPR 55 MND 2 PATK 10 SPD 10 SLD 10 LCH 2 RFL 5 CRT 5 SKL 3 PDEF 7 MDEF 3 AAA 8 CRTR 3 ENDAMULET
1807 1000 1 1 1 1
BLADE 291 127 127 108 150 1
DEVOUR 283 119 150 150 97 0
THORN 293 97 144 150 125 0
HUNT 295 125 150 104 137 0
7 SHI FENG BI SHANG ZHI HONG JUE
```
计算过程如下：
![计算](https://p.inari.site/guest/23-09/11/64fe7149caa95.png)
己方初始物攻（计算FENG后）=146755，己方魔攻=26575
物伤（暴击技能）=((上回合物攻+(上回合物攻+魔攻)\*0.2\*回合数)\*2(暴击)+本回合物攻\*3)\*1.1(护符)
绝伤=本回合物攻/2
可以看出物伤部分暴击处理的确在技能之前，但神秘刃绝伤是在技能之后。
物伤取整方面有点小问题，不应该把物攻先取整再算的，但实际怎么取整我也不清楚（

**Comment by ilusrdbb** [comment]
神秘刃结算确实是在FENG之后，TIAO应该也同理
对于雅来说是先发动技能的提升物攻效果再结算神秘刃，很反直觉，我先照着实际情况改

**Comment by ilusrdbb** [comment]
改好发布了，我这边拿你的数据测试基本符合，如果没问题这个issue就关了吧
最后感谢提供测试数据
