### ISSUE TITLE
忍无可忍触发回合数计算有误

### ISSUE THREAD

**Issue by Testla** [ilusrdbb/guguzhen-loganalysis#19]
最近按照 <https://bbs.kfpromax.com/read.php?tid=1016660&sf=ba1> 的思路算了一套配置来打野。虽然计算器算出的胜率超过 99%，实战却偶尔会输。用计算器复盘发现实战时玩家一直只能连续行动 3 个回合，而在计算器里回合数高了以后受热血战魂天赋的加成会开始连续行动 4 个回合。

测试数据如下。从帖子里复制的，为了让 bug 更快出现，修改了匕首的速度和野怪等级。

```plaintext
60

MING 300 100 4 8
WISH 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 1 551 46 1 378
DAGGER 100 100 120 150 100 0
DEVOUR 100 100 120 100 120 0
WOOD 100 120 100 120 100 0
HUNT 100 120 100 100 120 0
4 SHI YA RE ZHI

NPC
    SHI   30      0
ENDNPC

THREADS 8
SEEDMAX 1000000
TESTS 1000
CITEST 1.0
VERBOSE 1
REDUCERATE 3 10
PCWEIGHT 1 1
DEFENDER 0
```

运行后先 `ti NPC 0`，然后输入 3 次 `0` 就能看到。

问题出在触发忍无可忍所需回合数的计算。<https://github.com/ilusrdbb/guguzhen-loganalysis/blob/a7865e3442315edbec8c60f40376824a32238cf0/newkf.cpp#L2848-L2856> 这里玩家虽然速度快，但只有 1 点敏捷，显然不满足延后到第 5 轮的条件。应该只判断 `b[lastSide]` 的敏捷是否超过对方的 6 倍。

**Comment by ilusrdbb** [comment]
感谢提交bug，已合并更新
