### ISSUE TITLE
29日更新改动遗漏：生命或护盾回复加成已不再限定加点方式

### ISSUE THREAD

**Issue by wjinhui** [ilusrdbb/guguzhen-loganalysis#21]
https://github.com/ilusrdbb/guguzhen-loganalysis/blob/91eb72f4f76f50694ef0fee2530ff4439cd2f908/newkf.cpp#L2145-L2146
https://github.com/ilusrdbb/guguzhen-loganalysis/blob/91eb72f4f76f50694ef0fee2530ff4439cd2f908/newkf.cpp#L2182-L2183
这两处漏改了，更新后已经不要求200/500点力量或智力

**Comment by ilusrdbb** [comment]
感谢提出问题，已修复
