### ISSUE TITLE
config文件问题

### ISSUE THREAD

**Issue by KaiwenTan** [ilusrdbb/guguzhen-loganalysis#3]
我是虚空叛逆帝龙，说一下config设计的一些问题：
1.能否说明一下白名单黑名单填写规则？
2.
# 默认护符 默认带XUE绑定REC 10
DEFAULT_AMULET = 'SKL 10 CRT 10 PDEF 10 MDEF 10'
默认全员有REC 10的话是直接加上吗？因为大部分飓风希实际上都是有REC 10而不带XUE。
所以不如全部默认都有REC 10。
3.
# 速度阈值，大于此速度的卷逼最终速度再乘1.1的速度葡萄
SPEED_ADD = 5000
实际上低速默、艾、弓还是有很多带1.1的速度葡萄，保证内战优势。
舞计算时这样附加会出现大问题，因为舞的被动加成和葡萄是一起算的，是战斗面板数值*1.4。你提前*1.1数值会出现较大误差。不如在护符填写时默认全体有1.1速度葡萄。
4.
# 剑盾是否需要加上10反伤樱桃
IS_ADD_RFL = True
实际上除了剑盾，大部分默、艾、冥都有10反伤樱桃，不如默认全体附加。
其他没什么问题（最好能识别图片，红的弓、重甲才默认有神秘

**Comment by ilusrdbb** [comment]
1 例子 ['虚空叛逆帝龙', 'ilusrdbb']
2 我认为默认全带影响会更大，日后会改成配置，用户自己选择是否默认
3 我不清楚舞是最后还要乘1.4，日后速度葡萄也改成可配置项，还有魔攻物攻葡萄也该这么做但是一直懒的搞
4 同上改成配置项，我觉得不能一棒子全默认
5 识别装备颜色正考虑搞

**Comment by KaiwenTan** [comment]
> 1 例子 ['虚空叛逆帝龙', 'ilusrdbb'] 2 我认为默认全带影响会更大，日后会改成配置，用户自己选择是否默认 3 我不清楚舞是最后还要乘1.4，日后速度葡萄也改成可配置项，还有魔攻物攻葡萄也该这么做但是一直懒的搞 4 同上改成配置项，我觉得不能一棒子全默认 5 识别装备颜色正考虑搞

战斗面板的速度照填就好，战斗时葡萄和被动的速度会自动计算不反映在战斗面板上，所以速度葡萄直接写在护符上就好。

**Comment by KaiwenTan** [comment]
以防万一说一下，吸血LCH和反伤RFL樱桃、及鲜血渴望、破壁、破魔在STAT中是要自己在战斗数据中加上的。就是AMULET中的LCH 10、RFL 10及光环BI、MO是没有任何作用的，而光环XUE只提供15%生命回复，10吸血要自己加上去。如果你已经知道就当我没说。

**Comment by KaiwenTan** [comment]
葡萄的话都不显示在战斗面板上，在AMULET中会起作用，所以你葡萄给全10%都没什么问题。

**Comment by ilusrdbb** [comment]
这个我知道，你不会在pc中见到mo、bi之类的天赋，xue的10吸血是加进去的

**Comment by ilusrdbb** [comment]
此issue的需求都已添加 @KaiwenTan

**Comment by KaiwenTan** [comment]
> 此issue的需求都已添加 @KaiwenTan
这个报错是？
 File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\gear.py", line 29, in get_red_list
    color_list = [int(battle_log_dom.xpath(XPATH_CONFIG['COLOR'])[4][-7:-6]),

ValueError: invalid literal for int() with base 10: '_'

**Comment by ilusrdbb** [comment]
我这边没遇到这个问题，样本太少了
这里截取装备颜色的时候偷懒写死了，我用回正则吧

**Comment by ilusrdbb** [comment]
再试下，如果还不行就可能是数据太过古早而存在无装备的垃圾数据 @KaiwenTan

**Comment by KaiwenTan** [comment]
> 再试下，如果还不行就可能是数据太过古早而存在无装备的垃圾数据 @KaiwenTan
  File "C:\Users\Administrator\Desktop\vnr\咕咕镇计算器\guguzhen-loganalysis-master\core\gear.py", line 30, in get_red_list
    color_list = [int(re.findall(MATCH_CONFIG['COLOR'], battle_log_dom.xpath(XPATH_CONFIG['COLOR'])[4])[0]),

ValueError: invalid literal for int() with base 10: 'z2104_4'
又出了那么奇怪的错误，加qq发你收割机记录吧，274766087
