### ISSUE TITLE
除了刚才提的config文件外的建议

### ISSUE THREAD

**Issue by KaiwenTan** [ilusrdbb/guguzhen-loganalysis#4]
1.重复的人后续出现会用后面的覆盖吗？是的话最好。
2.有的角色专注于防守，比如薇和1.4w速的匕首飓风，刃琳刃希，短杖打野默，匕首梦，摆烂希琳。能否添加判断DEF的条件？当然我已经列举全了。

**Comment by KaiwenTan** [comment]
我思考了一下判断标准，角色、装备、等级、速度，这3项判断对方是否专用于防守。
如角色是薇就附加DEF，角色是默带短杖而且等级低于800就附加DEF，角色是梦带匕首就附加DEF。

**Comment by KaiwenTan** [comment]
我思考了一下判断标准，角色、装备、等级、属性，这4项判断对方是否专用于防守。
如角色是薇就附加DEF，角色是默带短杖而且等级低于800就附加DEF，角色是梦带匕首就附加DEF，匕首有1.4w速就附加DEF。

**Comment by ilusrdbb** [comment]
1 是的
2 配置里无法做到太过精细的判断，首先我是拒绝在代码里写死大量的额外逻辑，而且在装备全是脑补的情况下本工具本身就有一定的误差，太过精细个人感觉没必要

**Comment by KaiwenTan** [comment]
> 1 是的 2 配置里无法做到太过精细的判断，首先我是拒绝在代码里写死大量的额外逻辑，而且在装备全是脑补的情况下本工具本身就有一定的误差，太过精细个人感觉没必要

不过我平常就是自己判断是否要加DEF，有这些判断能减少工作量。现在一个个角色看过去也很辛苦啊。

**Comment by ilusrdbb** [comment]
姑且添加了防守模式中摆烂、打野、转盘的逻辑
你说的其他套路我不认为完全不存在出击的可能，3s环境隔一会就变，而且大多数人其实不用计算器，出击都随心所欲，本身与实际偏差就已经很大时再过于精细意义不大
你可以在__init__.get_defend_result中自行添加逻辑 @KaiwenTan

**Comment by ilusrdbb** [comment]
此需求不会再进一步开发，如有bug请另行提交issue，该issue关闭
