### ISSUE TITLE
防守模式能否在数据前加DEF而不是直接忽略

### ISSUE THREAD

**Issue by KaiwenTan** [ilusrdbb/guguzhen-loganalysis#5]
比如以下两人的数据我不想忽略，只要在前面加DEF即可。
DEF WEI_魔灯之灵_重甲秃鹫匕首薇 STAT
WISH 5 5 5 5 5 5 5
AMULET PATK 10 MATK 10 SPD 10 HP 10 SLD 10 CRT 10 SKL 10 PDEF 10 MDEF 10 ENDAMULET
10655 	17445 	0 			
0 	347 	0 	630 	0 	
11340 	943 	800 	2140 	800 	
155396 	6 	1600 	364 	7 	0 
1020 	630 	85 	90 		
5 XUE RE ZHI JU JUE
// level:808

DEF WEI_bahamutjr_袍秃鹫匕首薇 STAT
WISH 5 5 5 5 5 5 5
AMULET PATK 10 MATK 10 SPD 10 HP 10 SLD 10 CRT 10 SKL 10 PDEF 10 MDEF 10 ENDAMULET
33 	13953 	0 			
0 	2 	0 	727 	0 	
13412 	1259 	800 	1248 	0 	
20602 	0 	0 	659052 	6 	22000 
1273 	727 	10 	80 		
5 SHENG RE ZHI JU JUE
// level:850

我添加薇直接忽略不合理。
def get_defend_result(attribute_map, enemy_card, enemy_level):
    if 'SHIELD' in attribute_map['gear'] and enemy_card != 'AI':
        return True
    elif 'STAFF' in attribute_map['gear'] and enemy_card == 'MO' and enemy_level < 800:
        return True
    elif enemy_card == 'WEI':
        return True

**Comment by ilusrdbb** [comment]
建议运行两次并使用两套newkf.in，在计算器中分别指定具体的DEFENDER模式
有两张以上850满级卡的情况下没啥必要使用混合模式，我也懒得搞
