### ISSUE TITLE
技能“不动如山 SHAN”可能没有正确发挥作用

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#7]
如图，右侧防守方携带了“不动如山 SHAN”，并点了384点敏捷
游戏中的效果为：防守方受到3次攻击后，在第4回合触发“忍无可忍”攻击第1次
在“t <对手信息>”命令显示的战斗过程中，防守方在第2回合就攻击了第1次
![屏幕截图_20230503_000528](https://user-images.githubusercontent.com/53046162/235725694-fe00e8ca-1f96-45cb-b2cb-2713aaf4f4b9.png)
![屏幕截图_20230503_001416](https://user-images.githubusercontent.com/53046162/235726015-733a5f2e-06f1-4a9e-920c-c50948813898.png)

该技能在bpc等计算中是否正确发挥作用未知

另：战斗过程中的HP和SLD显示异常，这点不影响实际结果

**Comment by ilusrdbb** [comment]
感谢提出问题，原因是代码里的shan仅在第一回合生效
已改好，改的比较糙，还需测试

**Comment by Mulexe** [comment]
> 感谢提出问题，原因是代码里的shan仅在第一回合生效 已改好，改的比较糙，还需测试

感谢修复。
大致测试了下应该没问题，SHAN带REN未超6倍敏捷、带REN超过6倍敏捷、不带REN情况下的都正常
