### ISSUE TITLE
伊在攻击时拥有过高的魔法伤害（疑似被动“彩金对剑”的问题）

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#8]
如图，左侧进攻方冥的魔法防御大于物理防御，伊的被动“彩金对剑”提供的应为物理伤害。
在游戏中，伊暴击时魔法伤害为453点（未暴击时的魔法伤害为302点）；
在计算器的战斗过程中，伊暴击时魔法伤害为52750点（未暴击时的魔法伤害为35167点），均远高于游戏实际数值。
除魔法伤害外的物伤、绝伤均正常。
该情况在伊携带匕首、弓的时候均有出现。**但在携带“神秘彩金长剑”时，战斗过程中的魔法伤害是正常的**。
![屏幕截图 2023-05-04 133816](https://user-images.githubusercontent.com/53046162/236120290-fa508ef2-667b-4d21-86e9-b9bc853d28e6.png)
![屏幕截图 2023-05-04 133949](https://user-images.githubusercontent.com/53046162/236120456-c2608b4c-bd03-4dd1-94b0-e8041256a65f.png)

在计算器中测试，伊在攻击物防更多和魔防更多的对手时，造成的物理伤害和魔法伤害没有变化，可能是被动“彩金对剑”的问题

![屏幕截图 2023-05-04 140720](https://user-images.githubusercontent.com/53046162/236124269-a61ec922-daae-4979-8e7c-0669a3f32354.png)

![屏幕截图 2023-05-04 140802](https://user-images.githubusercontent.com/53046162/236124285-2547dfc2-837f-461c-8db1-edd8e390f9c1.png)

**Comment by ilusrdbb** [comment]
代码里对彩金神秘判断有误，导致伊这个神秘一直在生效，现已修复

**Comment by Mulexe** [comment]
> 代码里对彩金神秘判断有误，导致伊这个神秘一直在生效，现已修复

感谢修复。测试了下没问题了
