### ISSUE TITLE
无法释放技能和暴击

### ISSUE THREAD

**Issue by Mulexe** [ilusrdbb/guguzhen-loganalysis#9]
如图，t命令输出的战斗过程全程没有技能和暴击
在ti命令指定3技能和暴击、2暴击、1技能也均无效
![屏幕截图 2023-05-12 002149](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/452570b6-8739-4678-8fb3-0ca9054fd227)
![屏幕截图 2023-05-12 002432](https://github.com/ilusrdbb/guguzhen-loganalysis/assets/53046162/aec40538-997c-4682-b8ea-fd2a48b2a8fe)

**Comment by ilusrdbb** [comment]
已修复这个bug
